development:
  adapter: postgresql
  encoding: unicode
  database: bazaar_sq
  pool: 5
  username: franciscoacontellmonje
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bazaar_sq_test
  pool: 5
  username: franciscoacontellmonje
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bazaar_sq_production
  pool: 5
  username: franciscoacontellmonje
  password:
